name: 'Trivy CVE Scan'
description: 'Build Deckhouse module'
inputs:
  prod_registry:
    description: 'Prod registry host (e.g., registry.deckhouse.io)'
    required: true
  prod_registry_user:
    description: 'Username for prod registry authentication'
    required: true
  prod_registry_password:
    description: 'Password for prod registry authentication'
    required: true
  dev_registry:
    description: 'Dev-registry host (e.g., dev-registry.deckhouse.io)'
    required: true
  dev_registry_user:
    description: 'Username for dev-registry authentication'
    required: true
  dev_registry_password:
    description: 'Password for dev-registry authentication'
    required: true
  codeowners_repo_token:
    description: 'GitLab token for downloading CODEOWNERS configmap from private repository'
    required: true
  deckhouse_private_repo:
    description: 'Deckhouse private repository'
    required: true
  dd_url:
    description: 'DefectDojo API URL'
    required: true
  dd_token:
    description: 'DefectDojo API token'
    required: true
  source_tag:
    description: 'Tag to scan (e.g., main, v1.74.3, pr123, release-1.73)'
    required: true
  case:
    description: 'Scan type: deckhouse | external_modules | CSE'
    required: true
  cve_test_repo_git:
    description: 'cve_scan.sh repo'
    required: true
  cve_ssh_private_key:
    description: 'cve_scan.sh repo key'
    required: true
  external_module_name:
    description: 'External module name (required when case=external_modules)'
    required: false
    default: ''
  scan_several_lastest_releases:
    description: 'Scan multiple latest releases (true/false)'
    required: false
    default: 'false'
  latest_releases_amount:
    description: 'Number of latest releases to scan when scan_several_lastest_releases=true'
    required: false
    default: '3'
  module_prod_registry_custom_path:
    description: 'Custom path for external modules in production registry'
    required: false
    default: 'deckhouse/fe/modules'
  module_dev_registry_custom_path:
    description: 'Custom path for external modules in development registry'
    required: false
    default: 'sys/deckhouse-oss/modules'
  release_in_dev:
    description: 'If true, release tag will be searched in dev registry instead of prod'
    required: false
    default: 'false'
  digest_from_werf:
    description: 'Path to werf images tags file (for CSE external modules)'
    required: false
    default: 'images_tags_werf'
  scan_users:
    description: 'Enable user validation scan for CSE (true/false)'
    required: false
    default: 'false'
  workdir:
    description: 'Working directory for temporary files'
    required: false
    default: 'cve-scan'
  trivy_reports_log_output:
    description: 'Trivy log output level (0=off, 1=CVE only, 2=CVE+License)'
    required: false
    default: '2'

runs:
  using: "composite"
  steps:
    - name: Start ssh-agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.cve_ssh_private_key }}  # только ключ, не URL

    - name: Add host to known_hosts
      shell: bash
      run: |
        HOST=$(echo "${{ inputs.cve_test_repo_git }}" | sed -E 's/.*@([^:]+).*/\1/')
        mkdir -p ~/.ssh
        ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts 2>/dev/null

    - name: Clone repository
      shell: bash
      run: |
        rm -rf /tmp/cve-scan
        git clone --depth 1 ${{ inputs.cve_test_repo_git }} /tmp/cve-scripts
        cp /tmp/cve-scripts/* ./

    - name: Run Trivy CVE Scan
      shell: bash
      env:
        TRIVY_BIN_VERSION: "v0.67.2"
        TRIVY_REPO_ID: "2181"
        TRIVY_DB_URL: "${{ inputs.prod_registry }}/deckhouse/ee/security/trivy-db:2"
        TRIVY_JAVA_DB_URL: "${{ inputs.prod_registry }}/deckhouse/ee/security/trivy-java-db:1"
        TRIVY_POLICY_URL: "${{ inputs.prod_registry }}/deckhouse/ee/security/trivy-bdu:1"
        TRIVY_REPORTS_LOG_OUTPUT: "${{ inputs.trivy_reports_log_output }}"
        PROD_REGISTRY: "${{ inputs.prod_registry }}"
        PROD_REGISTRY_USER: "${{ inputs.prod_registry_user }}"
        PROD_REGISTRY_PASSWORD: "${{ inputs.prod_registry_password }}"
        DEV_REGISTRY: "${{ inputs.dev_registry }}"
        DEV_REGISTRY_USER: "${{ inputs.dev_registry_user }}"
        DEV_REGISTRY_PASSWORD: "${{ inputs.dev_registry_password }}"
        SOURCE_TAG: "${{ inputs.source_tag }}"
        CASE: "${{ inputs.case }}"
        EXTERNAL_MODULE_NAME: "${{ inputs.external_module_name }}"
        RELEASE_IN_DEV: "${{ inputs.release_in_dev }}"
        SCAN_USERS: "${{ inputs.scan_users }}"
        SCAN_SEVERAL_LATEST_RELEASES: "${{ inputs.scan_several_lastest_releases }}"
        LATEST_RELEASES_AMOUNT: "${{ inputs.latest_releases_amount }}"
        MODULE_PROD_REGISTRY_CUSTOM_PATH: "${{ inputs.module_prod_registry_custom_path }}"
        MODULE_DEV_REGISTRY_CUSTOM_PATH: "${{ inputs.module_dev_registry_custom_path }}"
        DIGEST_FROM_WERF: "${{ inputs.digest_from_werf }}"
        DD_URL: "${{ inputs.dd_url }}"
        DD_TOKEN: "${{ inputs.dd_token }}"
        CODEOWNERS_REPO_TOKEN: "${{ inputs.codeowners_repo_token }}"
        DECKHOUSE_PRIVATE_REPO: "${{ inputs.deckhouse_private_repo }}"
        CONFIGMAP_PROJECT_ID: "4352"
        WORKDIR: "${{ github.workspace }}/${{ inputs.workdir }}"
      run: |
        ./cve_scan.sh

