name: 'Setup TRDL'
description: 'Install TRDL with versioned releases and symlink pattern to prevent race conditions'

runs:
  using: 'composite'
  steps:
    - name: Setup TRDL
      shell: bash
      run: |
        set -e
        
        TRDL_ROOT="${HOME}/.trdl"
        
        echo "ðŸ” Getting TRDL version from stable channel..."
        trdl_target_version=$(curl -sSf https://tuf.trdl.dev/targets/channels/0/stable)
        
        if [[ -z "$trdl_target_version" ]]; then
          echo "::error::Failed to get TRDL version from stable channel"
          exit 1
        fi
        
        echo "ðŸ“¦ Target TRDL version: $trdl_target_version"
        
        TRDL_BIN="${TRDL_ROOT}/releases/${trdl_target_version}/trdl"
        
        if [[ ! -x "${TRDL_BIN}" ]]; then
          echo "ðŸ“¥ Installing TRDL ${trdl_target_version}..."
          mkdir -p "${TRDL_ROOT}/releases/${trdl_target_version}"
          
          curl -sSLO "https://tuf.trdl.dev/targets/releases/${trdl_target_version}/linux-amd64/bin/trdl"
          mv trdl "${TRDL_BIN}"
          
          chmod +x "${TRDL_BIN}"
          
          echo "âœ… TRDL ${trdl_target_version} installed"
        else
          echo "âœ… TRDL ${trdl_target_version} already installed"
        fi
        
        ln -sfn "releases/${trdl_target_version}" "${TRDL_ROOT}/current"
        
        echo "${TRDL_ROOT}/current" >> $GITHUB_PATH
        
        echo "âœ… TRDL ready to use (version: ${trdl_target_version})"

