on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/lint@v4

  build:
    runs-on: ubuntu-latest
    name: Build and Push images
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/setup@v4
        with:
          registry: registry.deckhouse.io
          registry_login: ${{ secrets.REGISTRY_LOGIN }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: deckhouse/modules-actions/build@v4
        with:
          module_source: registry.deckhouse.io/deckhouse/ce/modules
          module_name: everything-controller
          module_tag: ${{ github.ref_name }}
          source_repo: ${{ secrets.SOURCE_REPO }}
          source_repo_ssh_key: ${{ secrets.SOURCE_REPO_SSH_KEY }}
          svace_enabled: ${{ github.event.inputs.svace_enabled || contains(github.event.pull_request.labels.*.name, 'analyze/svace') }}
          svace_analyze_host: "${{ secrets.SVACE_ANALYZE_HOST }}"
          svace_analyze_ssh_user: "${{ secrets.SVACE_ANALYZE_SSH_USER }}"
          svace_analyze_ssh_key: "${{ secrets.SVACE_ANALYZE_SSH_PRIVATE_KEY }}"
          werf_sign_cert: "${{ secrets.WERF_SIGN_CERT }}"
          werf_sign_intermediates: "${{ secrets.WERF_SIGN_INTERMEDIATES }}"
          werf_sign_key: "${{ secrets.WERF_SIGN_KEY }}"
          vault_addr: "${{ secrets.VAULT_ADDR }}"
          vault_role_id: "${{ secrets.VAULT_ROLE_ID }}"
          vault_secret_id: "${{ secrets.VAULT_SECRET_ID }}"
          transit_secret_engine_path: "${{ secrets.TRANSIT_SECRET_ENGINE_PATH }}"
          werf_sign_elf_files: "1"
          werf_bsign_elf_files: "1"