name: CVE Scan

on:
  schedule:
    - cron: '0 01 * * 0,3'
  pull_request:
    types: [opened, reopened, labeled, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      source_tag:
        description: "release version in semver minor format (example: 1.68) or specified tag from dev registry"
        required: false
      scan_several_lastest_releases:
        description: 'Optional. Whether to scan last several releases or not. true/false. For scheduled pipelines it is always true. Default is: false.'
        required: false
      latest_releases_amount:
        description: 'Optional. Number of latest releases to scan. Default is: 3'
        required: false
      trivy_reports_log_output:
        description: 'Optional. Output Trivy reports to the CI/CD log. 0 - do not output, 1 - CVE/FS only, 2 - CVE + License. Default: 1'
        required: false
      external_module_name:
        description: 'The name of the module whose tag will be scanned'
        required: false

jobs:
  cve_scan_on_pr:
    if: github.event_name == 'pull_request'
    name: CVE scan for PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/cve_scan@main
        with:
          case: "deckhouse"
          source_tag: "${{ github.event.inputs.source_tag }}"
          trivy_reports_log_output: "${{ github.event.inputs.trivy_reports_log_output }}"
          scan_several_lastest_releases: "${{ github.event.inputs.scan_several_lastest_releases }}"
          latest_releases_amount: "${{ github.event.inputs.latest_releases_amount }}"
          prod_registry: "registry.deckhouse.io"
          prod_registry_user: "${{ secrets.DECKHOUSE_REGISTRY_READ_USER }}"
          prod_registry_password: "${{ secrets.DECKHOUSE_REGISTRY_READ_PASSWORD }}"
          dev_registry: "dev-registry.deckhouse.io"
          dev_registry_user: "${{ secrets.DECKHOUSE_DEV_REGISTRY_USER}}"
          dev_registry_password: "${{ secrets.DECKHOUSE_DEV_REGISTRY_PASSWORD }}"
          codeowners_repo_token: "${{ secrets.CODEOWNERS_REPO_TOKEN }}"
          deckhouse_private_repo: "${{ secrets.DECKHOUSE_PRIVATE_REPO }}"
          dd_url: "${{ secrets.DD_URL }}"
          dd_token: "${{ secrets.DD_TOKEN }}"
          cve_test_repo_git: "${{ secrets.CVE_TEST_REPO_GIT }}"
          cve_ssh_private_key: "${{ secrets.CVE_SSH_PRIVATE_KEY }}"
  cve_scan:
    if: github.event_name != 'pull_request'
    name: Regular CVE scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/cve_scan@main
        with:
          case: "External Modules"
          external_module_name: "${{ github.event.inputs.external_module_name }}"
          source_tag: "${{ github.event.inputs.source_tag }}"
          release_in_dev: "${{ github.event.inputs.release_in_dev }}"
          trivy_reports_log_output: "${{ github.event.inputs.trivy_reports_log_output }}"
          scan_several_lastest_releases: "${{ github.event.inputs.scan_several_lastest_releases }}"
          latest_releases_amount: "${{ github.event.inputs.latest_releases_amount }}"
          prod_registry: "registry.deckhouse.io"
          prod_registry_user: "${{ secrets.DECKHOUSE_REGISTRY_READ_USER }}"
          prod_registry_password: "${{ secrets.DECKHOUSE_REGISTRY_READ_PASSWORD }}"
          dev_registry: "dev-registry.deckhouse.io"
          dev_registry_user: "${{ secrets.DECKHOUSE_DEV_REGISTRY_USER}}"
          dev_registry_password: "${{ secrets.DECKHOUSE_DEV_REGISTRY_PASSWORD }}"
          codeowners_repo_token: "${{ secrets.CODEOWNERS_REPO_TOKEN }}"
          deckhouse_private_repo: "${{ secrets.DECKHOUSE_PRIVATE_REPO }}"
          dd_url: "${{ secrets.DD_URL }}"
          dd_token: "${{ secrets.DD_TOKEN }}"
          cve_test_repo_git: "${{ secrets.CVE_TEST_REPO_GIT }}"
          cve_ssh_private_key: "${{ secrets.CVE_SSH_PRIVATE_KEY }}"
