on:
  workflow_dispatch:
    inputs:
      svace_enabled:
        description: 'A boolean value which indicates whether svace analyze will be performed'
        required: false

## NOTE: to perform static analysis sources must be built using svace build and uploaded to svace analyze server to the correct location preserving strict directory hierarchy
jobs:
  analyze_module:
    if: ${{ github.event.inputs.svace_enabled == true }}
    name: Module static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: deckhouse/modules-actions/svace_analyze@v2
        with:
          ci_commit_ref_name: ${{ github.event.pull_request.head.ref }}
          ci_commit_hash: ${{ github.event.pull_request.head.sha }}
          svace_analyze_host: "${{ secrets.SVACE_ANALYZE_HOST }}"
          svace_analyze_ssh_user: "${{ secrets.SVACE_ANALYZE_SSH_USER }}"
          svacer_url: "${{ secrets.SVACER_URL }}"
          svacer_import_user: "${{ secrets.SVACER_IMPORT_USER }}"
          svacer_import_password: "${{ secrets.SVACER_IMPORT_PASSWORD }}"
          svace_analyze_ssh_private_key: "${{ secrets.SVACE_ANALYZE_SSH_PRIVATE_KEY }}"
