name: 'Setup Deckhouse Module Building Environment'
description: 'Setup Deckhouse Module'
inputs:
  registry:
    description: 'Registry URL'
    required: true
  registry_login:
    description: 'Registry login'
    required: true
  registry_password:
    description: 'Registry password'
    required: true

runs:
  using: "composite"
  steps:
    - uses: werf/actions/install@v2
    - uses: imjasonh/setup-crane@v0.4

    - name: Print werf version
      shell: bash
      run: werf version

    - name: Print crane version
      shell: bash
      run: crane version

    - name: Login into registry ${{ inputs.registry }}
      shell: bash
      run: werf cr login -u ${{ inputs.registry_login }} -p ${{ inputs.registry_password }} ${{ inputs.registry }}
