name: 'Setup Deckhouse Module Building Environment'
description: 'Setup Deckhouse Module'
inputs:
  registry:
    description: 'Registry URL'
    required: true
  registry_login:
    description: 'Registry login'
    required: true
  registry_password:
    description: 'Registry password'
    required: true
  werf_version:
    description: 'Werf version'
    required: true
  fox_access_token:
    description: 'FOX GitLab access token for downloading werf'
    required: true
  deckhouse_private_repo:
    description: 'Deckhouse private repository URL'
    required: true

runs:
  using: "composite"
  steps:
    - uses: imjasonh/setup-crane@v0.4

    - name: Install werf
      shell: bash
      run: |
        curl --fail -sSL -o ~/bin/werf \
        -H "PRIVATE-TOKEN: ${{ inputs.fox_access_token }}" \
        "https://${{ inputs.deckhouse_private_repo }}/api/v4/projects/4052/packages/generic/werf/${{ inputs.werf_version }}/werf"
        chmod +x ~/bin/werf
        export PATH=~/bin:$PATH

    - name: Print werf version
      shell: bash
      run: werf version

    - name: Print crane version
      shell: bash
      run: crane version

    - name: Login into registry ${{ inputs.registry }}
      shell: bash
      run: werf cr login -u ${{ inputs.registry_login }} -p ${{ inputs.registry_password }} ${{ inputs.registry }}
