name: 'Install Module'
description: 'Install Deckhouse module'
runs:
  using: "composite"
  steps:
    - uses: werf/actions/install@v1.2
    - uses: imjasonh/setup-crane@v0.1

    - run: werf version
      shell: bash
      name: Werf version
      
    - run: crane version
      shell: bash
      name: Crane version

    - run: werf cr login -u ${{ MODULES_REGISTRY_LOGIN}} -p ${{  MODULES_REGISTRY_PASSWORD }} ${MODULES_REGISTRY}
      shell: bash
      name: Werf login registry
